name: NodeMCU 1.0 Build

on: [push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Setup ESP8266 Core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Install Libraries
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "NTPClient"
          arduino-cli lib install "Time"
          arduino-cli lib install "Ticker"
          arduino-cli lib install "ESPAsyncTCP"
          arduino-cli lib install "ESP Async WebServer"
          arduino-cli lib install "ElegantOTA"
          arduino-cli lib install "UniversalTelegramBot"

      - name: Compile for NodeMCU 1.0
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --output-dir ./build ./aqua

      - name: Save .bin File
        uses: actions/upload-artifact@v4
        with:
          name: NodeMCU-Firmware
          path: ./build/*.bin
